version: '3'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./config/nginx-sites/api.conf:/etc/nginx/sites-available/api.conf
      - ./config/nginx-sites/default.conf:/etc/nginx/sites-available/default.conf
      - ./config/fastcgi.conf:/etc/nginx/snippets/fastcgi-php.conf
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./config/certs/nginx-selfsigned.crt:/etc/nginx/ssl/localhost.crt
      - ./config/certs/nginx-selfsigned.key:/etc/nginx/ssl/localhost.key
      - ./scripts/nginx-install.sh:/docker-entrypoint.d/nginx-install.sh
      - ./angular/dist/angular-code-share/:/var/www/html/angular/
      - ./codeigniter/:/var/www/html/ci-api
    ports:
      - "8080:80"
      - "443:443"
  db:
    image: mariadb
    container_name: maria
    volumes:
      - ./createremote.sql:/docker-entrypoint-initdb.d/createremote.sql
    environment: 
      MYSQL_ROOT_PASSWORD: deadbeef
      MYSQL_DATABASE: code_share
      MYSQL_USER: remote
      MYSQL_PASSWORD: deadbeef
    ports:
      - "3306:3306"
    tty: true